/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as LainnyaRouteImport } from './routes/lainnya'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PasarRouteImport } from './routes/pasar'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminBeritaRouteImport } from './routes/admin.berita'
import { Route as AdminMataUangRouteImport } from './routes/admin.mata-uang'
import { Route as AdminReferralRouteImport } from './routes/admin.referral'
import { Route as AdminSinyalRouteImport } from './routes/admin.sinyal'
import { Route as AdminTopUpRouteImport } from './routes/admin.top-up'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWithdrawRouteImport } from './routes/admin.withdraw'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaRoute = LainnyaRouteImport.update({
  id: '/lainnya',
  path: '/lainnya',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PasarRoute = PasarRouteImport.update({
  id: '/pasar',
  path: '/pasar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMataUangRoute = AdminMataUangRouteImport.update({
  id: '/mata-uang',
  path: '/mata-uang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralRoute = AdminReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSinyalRoute = AdminSinyalRouteImport.update({
  id: '/sinyal',
  path: '/sinyal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopUpRoute = AdminTopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawRoute = AdminWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AdminRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeritaRoute,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeritaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beranda': typeof BerandaRoute
  '/berita': typeof BeritaRouteWithChildren
  '/deposit': typeof DepositRoute
  '/lainnya': typeof LainnyaRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/pasar': typeof PasarRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trade': typeof TradeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/mata-uang': typeof AdminMataUangRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/sinyal': typeof AdminSinyalRoute
  '/admin/top-up': typeof AdminTopUpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita/': typeof BeritaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beranda': typeof BerandaRoute
  '/deposit': typeof DepositRoute
  '/lainnya': typeof LainnyaRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/pasar': typeof PasarRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trade': typeof TradeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/mata-uang': typeof AdminMataUangRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/sinyal': typeof AdminSinyalRoute
  '/admin/top-up': typeof AdminTopUpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita': typeof BeritaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beranda': typeof BerandaRoute
  '/berita': typeof BeritaRouteWithChildren
  '/deposit': typeof DepositRoute
  '/lainnya': typeof LainnyaRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/pasar': typeof PasarRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/trade': typeof TradeRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/mata-uang': typeof AdminMataUangRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/sinyal': typeof AdminSinyalRoute
  '/admin/top-up': typeof AdminTopUpRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita/': typeof BeritaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beranda'
    | '/berita'
    | '/deposit'
    | '/lainnya'
    | '/login'
    | '/order'
    | '/pasar'
    | '/profil'
    | '/referral'
    | '/register'
    | '/trade'
    | '/withdraw'
    | '/admin/berita'
    | '/admin/mata-uang'
    | '/admin/referral'
    | '/admin/sinyal'
    | '/admin/top-up'
    | '/admin/users'
    | '/admin/withdraw'
    | '/berita/$slug'
    | '/berita/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/beranda'
    | '/deposit'
    | '/lainnya'
    | '/login'
    | '/order'
    | '/pasar'
    | '/profil'
    | '/referral'
    | '/register'
    | '/trade'
    | '/withdraw'
    | '/admin/berita'
    | '/admin/mata-uang'
    | '/admin/referral'
    | '/admin/sinyal'
    | '/admin/top-up'
    | '/admin/users'
    | '/admin/withdraw'
    | '/berita/$slug'
    | '/berita'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beranda'
    | '/berita'
    | '/deposit'
    | '/lainnya'
    | '/login'
    | '/order'
    | '/pasar'
    | '/profil'
    | '/referral'
    | '/register'
    | '/trade'
    | '/withdraw'
    | '/admin/berita'
    | '/admin/mata-uang'
    | '/admin/referral'
    | '/admin/sinyal'
    | '/admin/top-up'
    | '/admin/users'
    | '/admin/withdraw'
    | '/berita/$slug'
    | '/berita/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BerandaRoute: typeof BerandaRoute
  BeritaRoute: typeof BeritaRouteWithChildren
  DepositRoute: typeof DepositRoute
  LainnyaRoute: typeof LainnyaRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  PasarRoute: typeof PasarRoute
  ProfilRoute: typeof ProfilRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  TradeRoute: typeof TradeRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya': {
      id: '/lainnya'
      path: '/lainnya'
      fullPath: '/lainnya'
      preLoaderRoute: typeof LainnyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasar': {
      id: '/pasar'
      path: '/pasar'
      fullPath: '/pasar'
      preLoaderRoute: typeof PasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mata-uang': {
      id: '/admin/mata-uang'
      path: '/mata-uang'
      fullPath: '/admin/mata-uang'
      preLoaderRoute: typeof AdminMataUangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referral': {
      id: '/admin/referral'
      path: '/referral'
      fullPath: '/admin/referral'
      preLoaderRoute: typeof AdminReferralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sinyal': {
      id: '/admin/sinyal'
      path: '/sinyal'
      fullPath: '/admin/sinyal'
      preLoaderRoute: typeof AdminSinyalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/top-up': {
      id: '/admin/top-up'
      path: '/top-up'
      fullPath: '/admin/top-up'
      preLoaderRoute: typeof AdminTopUpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdraw': {
      id: '/admin/withdraw'
      path: '/withdraw'
      fullPath: '/admin/withdraw'
      preLoaderRoute: typeof AdminWithdrawRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof BeritaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminMataUangRoute: typeof AdminMataUangRoute
  AdminReferralRoute: typeof AdminReferralRoute
  AdminSinyalRoute: typeof AdminSinyalRoute
  AdminTopUpRoute: typeof AdminTopUpRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawRoute: typeof AdminWithdrawRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBeritaRoute: AdminBeritaRoute,
  AdminMataUangRoute: AdminMataUangRoute,
  AdminReferralRoute: AdminReferralRoute,
  AdminSinyalRoute: AdminSinyalRoute,
  AdminTopUpRoute: AdminTopUpRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawRoute: AdminWithdrawRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BeritaRouteChildren {
  BeritaSlugRoute: typeof BeritaSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
}

const BeritaRouteChildren: BeritaRouteChildren = {
  BeritaSlugRoute: BeritaSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
}

const BeritaRouteWithChildren =
  BeritaRoute._addFileChildren(BeritaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BerandaRoute: BerandaRoute,
  BeritaRoute: BeritaRouteWithChildren,
  DepositRoute: DepositRoute,
  LainnyaRoute: LainnyaRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  PasarRoute: PasarRoute,
  ProfilRoute: ProfilRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  TradeRoute: TradeRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
